[project]
name = "stacks-savings-vault"
description = "A secure savings vault smart contract for the Stacks blockchain"
authors = []
telemetry = true
requirements = []
boot_contracts = ["pox-4"]

[contracts.savings-vault]
path = "contracts/savings-vault.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
